//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupStatistic
    {
        public GroupStatistic()
        {
            this.GroupTime = new HashSet<GroupTime>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDStudent { get; set; }
        public Nullable<int> IDLesson { get; set; }
    
        public virtual ICollection<GroupTime> GroupTime { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Student Student { get; set; }
    }
}
