//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupTime
    {
        public int ID { get; set; }
        public Nullable<int> IDTimetable { get; set; }
        public Nullable<int> IDGroup { get; set; }
        public bool IsVisited { get; set; }
    
        public virtual GroupStatistic GroupStatistic { get; set; }
        public virtual Timetable Timetable { get; set; }
    }
}
