//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class School6Entities1 : DbContext
    {
        public School6Entities1()
            : base("name=School6Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Education> Education { get; set; }
        public DbSet<GroupStatistic> GroupStatistic { get; set; }
        public DbSet<GroupTime> GroupTime { get; set; }
        public DbSet<Lesson> Lesson { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Student> Student { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Teacher> Teacher { get; set; }
        public DbSet<Timetable> Timetable { get; set; }
        public DbSet<TimeLesson> TimeLesson { get; set; }
    }
}
