//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public Timetable()
        {
            this.GroupTime = new HashSet<GroupTime>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> IDTimeLesson { get; set; }
    
        public virtual ICollection<GroupTime> GroupTime { get; set; }
        public virtual TimeLesson TimeLesson { get; set; }
    }
}
