//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeLesson
    {
        public TimeLesson()
        {
            this.Timetable = new HashSet<Timetable>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateLesson { get; set; }
        public Nullable<System.TimeSpan> TimeLessons { get; set; }
        public string Classroom { get; set; }
        public Nullable<int> IDLesson { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual ICollection<Timetable> Timetable { get; set; }
    }
}
