//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int ID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> IDTimeLesson { get; set; }
        public Nullable<int> IDGroup { get; set; }
    
        public virtual GroupStatistic GroupStatistic { get; set; }
        public virtual TimeLesson TimeLesson { get; set; }
    }
}
